services:
  nginx:
    build: .
    container_name: nginx_45
    ports:
      - "8081:80"  
    volumes:
      - ./public:/usr/share/nginx/html


  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk11
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - "./jenkins:/var/jenkins_home"

    

  